
[package]
name = "solana-bpf-solvei"
version = "0.0.1"
description = "Solana Social Media, the Web3 Vei!"
authors = ["Marcus Pousette <marcus.pousette@live.com>"]
license = "Apache-2.0"
edition = "2018"


[features]
no-entrypoint = []
test-bpf = []

[dependencies]
borsh = "0.9.1"
borsh-derive = "0.9.1"
solana-program = "=1.7.9"
arrayref = "0.3.6"


[dev-dependencies]
solana-program-test = "=1.7.9"
solana-sdk = "=1.7.9"

[lib]
name = "solvei"
crate-type = ["cdylib", "lib"]
