name: Hello Example
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: multiple paths
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: '${{ runner.os }}-${{ hashFiles(''TODO'') }}'
      - uses: actions/checkout@v2
      - run: |
          rustup install nightly
          cargo --version
          docker --version
      - run: >-
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - run: >-
          sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
      - name: Build test and deploy dev
        working-directory: ./src/program-rust
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl --allow-unauthenticated
          sudo apt-get install -y libssl-dev --allow-unauthenticated
          sudo apt-get install -y clang-7 --allow-unauthenticated
          sudo apt-get install -y libssl1.1 --allow-unauthenticated
          clang-7 --version
          sh -c "$(curl -sSfL https://release.solana.com/v1.7.8/install)"
          export PATH=~/.local/share/solana/install/active_release/bin:$PATH
          solana-install info
          echo ${{secrets.SOLANA_DEVELOPMENT_KEY}} >> /home/runner/.config/solana/id.json
          cargo build-bpf
          cargo test-bpf
          solana config set --url https://api.devnet.solana.com
          solana airdrop 10
          solana program deploy /home/runner/work/solvei-protocol/solvei-protocol/src/program-rust/target/deploy/solvei.so
